#
# Module manifest for module 'PSWindowsUpdate'
#
# Generated by: Michal Gajda
#
# Generated on: 2011-01-20
#
# Change Log:
# v1.5.6 - Added ValidateSet for Severity and NotSeverity params in Install-WindowsUpdate, Get-WindowsUpdate. Added MaxSize and MinSize params in Install-WindowsUpdate, Get-WindowsUpdate.
# v1.5.5 - Added RootCategories filter for Install-WindowsUpdate, Get-WindowsUpdate 
# v1.5.4 - Fixed small bugs
# v1.5.3 - Added Severity search option for Install-WindowsUpdate, Get-WindowsUpdate 
# v1.5.2 - Project migration to PSGallery. Added new aliases Install-WindowsUpdate...
# v1.5.1 - Added Add-WUServiceManager and Remove-WUServiceManager to register/unregister updates Service Manager. Added remoting to Get-WURebootStatus.
# v1.5.0 - Added Invoke-WUInstall for pseudo remoting and Update-WUModule to update module.
# v1.4.7 - Added AutoSelectOnly param for automatic accept only `important` updates, ie those  which have the status AutoSelectOnWebsites = true.
# v1.4.6 - Added function Hide-WUUpdate to auto hide updates that meets search criteria.
# v1.4.5 - Changed default search pre crteria isHidden = 0 to show only nothidden updates. Added WithHidden param to get all updates (hidden and not) and removed isNotHidden param (now it is default criteria). Added warning if don`t find any updates.
# v1.4.4 - Added NotCategory, NotKBArticleID, NotTitle param to filter updates that`s not match of these value.
# v1.4.3 - Added isNotHidden param to show only not hidden updates. Default still show whole updates (hidden and not hidden).
# v1.4.2 - Added IgroneReboot param to hide prompt for reboot, but do not reboot automaticaly.
# v1.4.1 - Added ability to define own search criteria. Correct fast ServerSelection param -WindowsUpdate and -MicrosoftUpdate.
# v1.4.0 - Code optimized, new  filtering criteria, simple remote to obtain information about updates.
# v1.3.4 - Fixed typographical bug in Get-WUInstall in type of updates.
# v1.3.3 - Added progress bar in Get-WUInstall.
# v1.3.2 - Fixed small bug in Add-WUOfflineSync.

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.5.2.6'

# ID used to uniquely identify this module
GUID = '8ed488ad-7c77-4b33-b06e-32214925163b'

# Author of this module
Author = 'Michal Gajda'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2011 Michal Gajda. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This module contain functions to manage Windows Update Client.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'PSWindowsUpdate.Format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = 'PSWindowsUpdate.psm1'

# Functions to export from this module
FunctionsToExport = 'Add-WUOfflineSync', 'Get-WUHistory', 'Get-WUInstall', 'Get-WUInstallerStatus',
					'Get-WUList', 'Get-WURebootStatus', 'Get-WUServiceManager', 'Get-WUUninstall',
					'Hide-WUUpdate', 'Invoke-WUInstall', 'Remove-WUOfflineSync',
					'Add-WUServiceManager','Remove-WUServiceManager'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = 'Install-WindowsUpdate', 'Uninstall-WindowsUpdate', 'Get-WindowsUpdate', 'Hide-WindowsUpdate'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'PSWindowsUpdate.psd1', 'PSWindowsUpdate.psm1', 'PSWindowsUpdate.Format.ps1xml'

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIOJgYJKoZIhvcNAQcCoIIOFzCCDhMCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU+vyzNjPbU91FoM1LShcB144z
# AhWgggnaMIIEmTCCA4GgAwIBAgIPFojwOSVeY45pFDkH5jMLMA0GCSqGSIb3DQEB
# BQUAMIGVMQswCQYDVQQGEwJVUzELMAkGA1UECBMCVVQxFzAVBgNVBAcTDlNhbHQg
# TGFrZSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxITAfBgNV
# BAsTGGh0dHA6Ly93d3cudXNlcnRydXN0LmNvbTEdMBsGA1UEAxMUVVROLVVTRVJG
# aXJzdC1PYmplY3QwHhcNMTUxMjMxMDAwMDAwWhcNMTkwNzA5MTg0MDM2WjCBhDEL
# MAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UE
# BxMHU2FsZm9yZDEaMBgGA1UEChMRQ09NT0RPIENBIExpbWl0ZWQxKjAoBgNVBAMT
# IUNPTU9ETyBTSEEtMSBUaW1lIFN0YW1waW5nIFNpZ25lcjCCASIwDQYJKoZIhvcN
# AQEBBQADggEPADCCAQoCggEBAOnpPd/XNwjJHjiyUlNCbSLxscQGBGue/YJ0UEN9
# xqC7H075AnEmse9D2IOMSPznD5d6muuc3qajDjscRBh1jnilF2n+SRik4rtcTv6O
# KlR6UPDV9syR55l51955lNeWM/4Og74iv2MWLKPdKBuvPavql9LxvwQQ5z1IRf0f
# aGXBf1mZacAiMQxibqdcZQEhsGPEIhgn7ub80gA9Ry6ouIZWXQTcExclbhzfRA8V
# zbfbpVd2Qm8AaIKZ0uPB3vCLlFdM7AiQIiHOIiuYDELmQpOUmJPv/QbZP7xbm1Q8
# ILHuatZHesWrgOkwmt7xpD9VTQoJNIp1KdJprZcPUL/4ygkCAwEAAaOB9DCB8TAf
# BgNVHSMEGDAWgBTa7WR0FJwUPKvdmam9WyhNizzJ2DAdBgNVHQ4EFgQUjmstM2v0
# M6eTsxOapeAK9xI1aogwDgYDVR0PAQH/BAQDAgbAMAwGA1UdEwEB/wQCMAAwFgYD
# VR0lAQH/BAwwCgYIKwYBBQUHAwgwQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL2Ny
# bC51c2VydHJ1c3QuY29tL1VUTi1VU0VSRmlyc3QtT2JqZWN0LmNybDA1BggrBgEF
# BQcBAQQpMCcwJQYIKwYBBQUHMAGGGWh0dHA6Ly9vY3NwLnVzZXJ0cnVzdC5jb20w
# DQYJKoZIhvcNAQEFBQADggEBALozJEBAjHzbWJ+zYJiy9cAx/usfblD2CuDk5oGt
# Joei3/2z2vRz8wD7KRuJGxU+22tSkyvErDmB1zxnV5o5NuAoCJrjOU+biQl/e8Vh
# f1mJMiUKaq4aPvCiJ6i2w7iH9xYESEE9XNjsn00gMQTZZaHtzWkHUxY93TYCCojr
# QOUGMAu4Fkvc77xVCf/GPhIudrPczkLv+XZX4bcKBUCYWJpdcRaTcYxlgepv84n3
# +3OttOe/2Y5vqgtPJfO44dXddZhogfiqwNGAwsTEOYnB9smebNd0+dmX+E/CmgrN
# Xo/4GengpZ/E8JIh5i15Jcki+cPwOoRXrToW9GOUEB1d0MYwggU5MIIEIaADAgEC
# AhMdAAABwiBugk+hmBENAAQAAAHCMA0GCSqGSIb3DQEBCwUAMDgxEzARBgoJkiaJ
# k/IsZAEZFgNjb20xEzARBgoJkiaJk/IsZAEZFgNhaGMxDDAKBgNVBAMTA0RDMTAe
# Fw0xODAyMjcxMzIyNTBaFw0xOTAyMjcxMzIyNTBaMFExEzARBgoJkiaJk/IsZAEZ
# FgNjb20xEzARBgoJkiaJk/IsZAEZFgNhaGMxDjAMBgNVBAMTBVVzZXJzMRUwEwYD
# VQQDEwxEYXZpZCBGcmF6ZXIwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOdZ
# VslEcUVBhkNOvls+hM6zPzqhxzaGKUSKtWXXyjl5GZMImD3C2os7yU2IZS6kLhzS
# 4yvAc6Zf6wU2vBXoO3IQwrIZw3u5AMs6xpgMlwWADnzCJ216sVWNsXuGd1ZggsUp
# kRQdzMdVndg9LEJk533LDcM0fJWzoujb9b2ZA16VAgMBAAGjggKlMIICoTAlBgkr
# BgEEAYI3FAIEGB4WAEMAbwBkAGUAUwBpAGcAbgBpAG4AZzATBgNVHSUEDDAKBggr
# BgEFBQcDAzALBgNVHQ8EBAMCB4AwHQYDVR0OBBYEFBfr/bmcdw1n7D05uQ0gb9iO
# SAWrMB8GA1UdIwQYMBaAFAdsf7rwI0TdTBUSbvvUyU92uK5eMIHmBgNVHR8Egd4w
# gdswgdiggdWggdKGgaVsZGFwOi8vL0NOPURDMSg0KSxDTj1kYzEsQ049Q0RQLENO
# PVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3Vy
# YXRpb24sREM9YWhjLERDPWNvbT9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jh
# c2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnSGKGh0dHA6Ly9kYzEu
# YWhjLmNvbS9DZXJ0RW5yb2xsL0RDMSg0KS5jcmwwgfMGCCsGAQUFBwEBBIHmMIHj
# MIGeBggrBgEFBQcwAoaBkWxkYXA6Ly8vQ049REMxLENOPUFJQSxDTj1QdWJsaWMl
# MjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERD
# PWFoYyxEQz1jb20/Y0FDZXJ0aWZpY2F0ZT9iYXNlP29iamVjdENsYXNzPWNlcnRp
# ZmljYXRpb25BdXRob3JpdHkwQAYIKwYBBQUHMAKGNGh0dHA6Ly9kYzEuYWhjLmNv
# bS9DZXJ0RW5yb2xsL2RjMS5haGMuY29tX0RDMSg0KS5jcnQwNwYDVR0RBDAwLqAs
# BgorBgEEAYI3FAIDoB4MHERhdmlkLkZyYXplckBhZHZob21lY2FyZS5vcmcwDQYJ
# KoZIhvcNAQELBQADggEBAJB0Yada34o5Mu3czVDv6FuI93dA1Q5rYTWGsyfCF/9L
# DLGsZ7ohaRAbLuryLc5tTuHaqCICdy1lCP2eW5V6oEWokkdH/66nJNJXSkiv48ML
# z7KRFbPUF0dT9JWRgW2avOciQANVPQb1R5dA24ekNb4ykvx1ojK2uriVr9fmMngI
# jwNra7xTFQBXJlN27cEzHNdGn2Z3XzZ2MBm0OtjdX+WC0GjDBbsW9Kr0FY+cMEH6
# abey3mD2p3RDn44ECFaxBBRBIUcgwluZK/ll34HOPnpo1oGi4btuypF6OC4RLkDS
# agacPC5GEoDtKJTFK7crXdzw+alC2sSY2tzV9CJr8wUxggO2MIIDsgIBATBPMDgx
# EzARBgoJkiaJk/IsZAEZFgNjb20xEzARBgoJkiaJk/IsZAEZFgNhaGMxDDAKBgNV
# BAMTA0RDMQITHQAAAcIgboJPoZgRDQAEAAABwjAJBgUrDgMCGgUAoHgwGAYKKwYB
# BAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAc
# BgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUZNfT
# qQPAZv08TKjvJAPoMgdOCOcwDQYJKoZIhvcNAQEBBQAEgYCot8y4nBmHFnz5N6xw
# L7pXNT5tdvalEBXpqVEgAIxkTKiJZjgCaQI/XJiqMfqtSuzmhTqUanrBeYRW7NY9
# rPMXjS3TlotDm/Br3WjMExlTLldl9ku6YWFI2dADp/TILGYoOz9ZWlm9FRQE7MRg
# I7udVNq6SnCflb0skzO7e2fe96GCAkMwggI/BgkqhkiG9w0BCQYxggIwMIICLAIB
# ATCBqTCBlTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAlVUMRcwFQYDVQQHEw5TYWx0
# IExha2UgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBOZXR3b3JrMSEwHwYD
# VQQLExhodHRwOi8vd3d3LnVzZXJ0cnVzdC5jb20xHTAbBgNVBAMTFFVUTi1VU0VS
# Rmlyc3QtT2JqZWN0Ag8WiPA5JV5jjmkUOQfmMwswCQYFKw4DAhoFAKBdMBgGCSqG
# SIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTE4MDYwNTE0MzAw
# MlowIwYJKoZIhvcNAQkEMRYEFO2Ivhk+eD/poeLzHbeg/RTTJ/3oMA0GCSqGSIb3
# DQEBAQUABIIBALBOChb3PqZSX4e3zYo6RSKMwM0jd5AHbZQvTRctCi5iHtVoEszA
# UBFMnEHz5O7ZhWioQi0LGFYpyfVJkZ7KPQR+U6PdSbP4acmtQpJxq5CMpjq/Glki
# NxSeSjvYTATphz8AP1ZLLLrEb0Ton9K2WSeEPIqz6aEZ4tRiXqFS3qLJHTxKHxfz
# w+pIYKRJr22f4rn+kNE3iMWR01RcchV8KsI4QqkRXHrWkKd4mxWbRMZcv9bkPFIP
# e4pbleyY5LexuHWbUMCQScDr9AwKsCXLKSjBOcLhjwY9JmE2NT3FckjK7Ydt83uO
# +oU+MZcctz6JNw+Ki6UXrs+aOOnFyUOeaC0=
# SIG # End signature block
